version: '3.1'

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mongo:3.6
    container_name: my-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
